# Generated by Django 3.0.5 on 2020-04-10 18:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pandaworker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='filetemplate',
            name='intervals',
            field=models.CharField(choices=[('DY', 'Daily'), ('WY', 'Weekly'), ('MY', 'Monthly')], default='DY', max_length=2),
        ),
        migrations.AddField(
            model_name='filetemplate',
            name='live_instances',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='filetemplate',
            name='save_history',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='ReportFlows',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feed_complete', models.BooleanField(default=False)),
                ('downstream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='downstream', to='pandaworker.FileTemplate')),
                ('upstream', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='upstream', to='pandaworker.FileTemplate')),
            ],
        ),
        migrations.CreateModel(
            name='LiveReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_id', models.IntegerField(blank=True)),
                ('live_file', models.FileField(blank=True, upload_to='')),
                ('live_data', models.CharField(blank=True, max_length=2000)),
                ('template', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pandaworker.FileTemplate')),
            ],
        ),
    ]
