# Generated by Django 3.0.5 on 2020-04-10 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pandaworker', '0002_auto_20200410_1332'),
    ]

    operations = [
        migrations.AlterField(
            model_name='livereport',
            name='live_data',
            field=models.CharField(blank=True, max_length=20000),
        ),
        migrations.AlterField(
            model_name='livereport',
            name='report_id',
            field=models.CharField(blank=True, max_length=200),
        ),
    ]
